version: 2.1
jobs:
        build:
                docker:
                        - image: selenium/standalone-chrome
                steps:
                        - run: sudo apt install default-jdk
                        - run: sudo apt install nginx
                        - checkout
                        - run: javac -cp /opt/selenium/selenium-server-standalone.jar clickmeTest.java
                        - run: |
                                cp default.conf /etc/nginx/conf.d
                                sudo nginx
                        - run: java -cp .:/opt/selenium/selenium-server-standalone.jar clickmeTest

