version: 2.1
jobs:
        build:
                docker:
                        - image: selenium/standalone-chrome
                steps:
                        - run: sudo apt-get update -qqy
                        - run: sudo apt-get -qqy install default-jdk 
                        - run: sudo apt-get -qqy install nginx
                        - checkout
                        - run: javac -cp /opt/selenium/selenium-server-standalone.jar clickmeTest.java
                        - run: |
                                #                                sudo cp default.conf /etc/nginx/conf.d
                                sudo cp index.html /usr/share/nginx/html
                                sudo nginx
                        - run: java -cp .:/opt/selenium/selenium-server-standalone.jar clickmeTest

