version: 2.1
jobs:
        build:
                docker:
                        - image: SeleniumHQ/docker-selenium/tree/master/StandaloneChrome
                steps:
                        - run: apt install default-jdk
                        - run: apt install nginx
                        - checkout
                        - run: javac -cp /opt/selenium/selenium-server-standalone.jar clickmeTest.java
                        - run: |
                                cp default.conf /etc/nginx/conf.d
                                nginx
                        - run: java -cp .:/opt/selenium/selenium-server-standalone.jar clickmeTest

