# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
    jobs:
            build:
                    docker:
                            - SeleniumHQ/docker-selenium/tree/master/StandaloneChrome


                    steps:
                            - run: apt install default-jdk
                            - run: apt install nginx
                            - checkout
                            - run: javac -cp /opt/selenium/selenium-server-standalone.jar clickmeTest.java
                            - run: |
                              cp default.conf /etc/nginx/conf.d
                              nginx
                            - run: java -cp .:/opt/selenium/selenium-server-standalone.jar clickmeTest
